/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9fa',
        'surface-dim': '#d9dadb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-soft': '#F0F2F5',
        'on-surface': '#191c1d',
        'on-surface-variant': '#40484b',
        outline: '#70787c',
        'outline-variant': '#c0c8cb',
        primary: '#003441',
        'on-primary': '#ffffff',
        'primary-container': '#0f4c5c',
        'on-primary-container': '#87bbce',
        'inverse-primary': '#9acee1',
        'primary-fixed': '#b6ebfe',
        'primary-fixed-dim': '#9acee1',
        'tertiary-fixed': '#ffdcbe',
        secondary: '#516161',
        'secondary-container': '#d4e6e5',
        'on-secondary-container': '#576867',
        tertiary: '#482700',
        'tertiary-container': '#623d13',
        warm: '#FAF9F6',
        'badge-sky': '#E3F2F7',
        'status-healthy': '#4ADE80',
        'status-warning': '#FBBF24',
        'status-severe': '#FB7185',
        error: '#ba1a1a',
      },
      fontFamily: {
        display: ['Outfit', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'ai-badge': ['11px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      maxWidth: {
        container: '640px',
        landing: '72rem',
        assess: '48rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'stack-gap': '32px',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
      },
      boxShadow: {
        elevated: '0 10px 20px rgba(0, 52, 65, 0.04)',
        soft: '0 4px 16px rgba(0, 52, 65, 0.06)',
        card: '0 8px 30px rgba(0, 52, 65, 0.06)',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
};
