-- MBTI-style personality test (4 dichotomies × 30 questions = 120)
-- 5-point agreement scale; 16 type profiles

create table if not exists public.personality_dichotomies (
  id serial primary key,
  code char(3) not null unique,
  pole_a char(1) not null,
  pole_b char(1) not null,
  label_a text not null,
  label_b text not null,
  description text,
  created_at timestamptz default now()
);

insert into public.personality_dichotomies (code, pole_a, pole_b, label_a, label_b, description) values
  ('E/I', 'E', 'I', 'Extraversion', 'Introversion',
   'How you direct and receive energy — outward through people and action, or inward through reflection and solitude.'),
  ('S/N', 'S', 'N', 'Sensing', 'Intuition',
   'How you take in information — through concrete facts and present detail, or through patterns, meaning, and future possibility.'),
  ('T/F', 'T', 'F', 'Thinking', 'Feeling',
   'How you make decisions — through objective logic and analysis, or through values, empathy, and relational impact.'),
  ('J/P', 'J', 'P', 'Judging', 'Perceiving',
   'How you approach structure — preferring planned, organised closure, or remaining open, flexible, and spontaneous.')
on conflict (code) do nothing;

create table if not exists public.personality_questions (
  id serial primary key,
  dichotomy_id int not null references public.personality_dichotomies(id) on delete cascade,
  question_number int not null unique,
  question_text text not null,
  scored_pole char(1) not null,
  created_at timestamptz default now()
);

-- E/I
insert into public.personality_questions (dichotomy_id, question_number, question_text, scored_pole) values
(1,  1,  'I feel energised after spending time with a large group of people.', 'E'),
(1,  2,  'I enjoy being the centre of attention in social situations.', 'E'),
(1,  3,  'I tend to think out loud and talk through problems with others.', 'E'),
(1,  4,  'I find it easy to approach strangers and start conversations.', 'E'),
(1,  5,  'I prefer working in an open, collaborative environment over working alone.', 'E'),
(1,  6,  'After a quiet weekend alone, I feel restless and eager to socialise.', 'E'),
(1,  7,  'I have a wide circle of acquaintances and enjoy keeping in touch with many people.', 'E'),
(1,  8,  'I jump into new experiences eagerly rather than observing from the sidelines.', 'E'),
(1,  9,  'I need time alone to recharge after socialising, even if I enjoyed it.', 'I'),
(1, 10,  'I prefer deep one-on-one conversations over group discussions.', 'I'),
(1, 11,  'I think carefully before I speak rather than voicing thoughts as they come.', 'I'),
(1, 12,  'I find large parties or noisy gatherings draining rather than exciting.', 'I'),
(1, 13,  'I keep a small, close-knit circle of friends rather than a wide social network.', 'I'),
(1, 14,  'I do my best work when I can focus without interruption.', 'I'),
(1, 15,  'I often feel overstimulated in busy, fast-paced environments.', 'I'),
-- S/N
(2, 16,  'I focus on what is real and present rather than what could be.', 'S'),
(2, 17,  'I trust experience and proven methods over untested theories.', 'S'),
(2, 18,  'I pay close attention to sensory details — sights, sounds, textures, and facts.', 'S'),
(2, 19,  'I prefer step-by-step instructions over open-ended guidelines.', 'S'),
(2, 20,  'I am practical and grounded; I value what works over what is imaginative.', 'S'),
(2, 21,  'I remember events in concrete, factual detail rather than impressions.', 'S'),
(2, 22,  'I prefer working with tangible outcomes I can see and measure.', 'S'),
(2, 23,  'I trust my five senses more than hunches or gut feelings.', 'S'),
(2, 24,  'I am more interested in what something means or implies than in the facts themselves.', 'N'),
(2, 25,  'I enjoy thinking about future possibilities and hypothetical scenarios.', 'N'),
(2, 26,  'I often notice patterns and connections that others miss.', 'N'),
(2, 27,  'I find routine and repetition boring — I crave novelty and new ideas.', 'N'),
(2, 28,  'I trust my intuition and hunches, even when I cannot fully explain them.', 'N'),
(2, 29,  'I prefer the big picture over the fine details.', 'N'),
(2, 30,  'I often imagine how things could be different or better rather than accepting them as they are.', 'N'),
-- T/F
(3, 31,  'I make decisions based on logic and objective analysis rather than feelings.', 'T'),
(3, 32,  'I find it easy to give critical feedback even when it may hurt someone.', 'T'),
(3, 33,  'I believe fairness means applying the same rules to everyone, regardless of circumstance.', 'T'),
(3, 34,  'I am more persuaded by a well-reasoned argument than by an emotional appeal.', 'T'),
(3, 35,  'I tend to be direct and blunt rather than softening my words to spare feelings.', 'T'),
(3, 36,  'When solving a conflict, I focus on finding the most rational solution over keeping the peace.', 'T'),
(3, 37,  'I am comfortable making tough decisions that are objectively correct but personally uncomfortable.', 'T'),
(3, 38,  'I evaluate ideas on their merits rather than on who proposed them.', 'T'),
(3, 39,  'I consider how decisions will affect other people before making them.', 'F'),
(3, 40,  'I find it important that everyone feels heard and included, even in group decisions.', 'F'),
(3, 41,  'I am highly attuned to the emotional atmosphere in a room.', 'F'),
(3, 42,  'I tend to soften criticism to preserve the other person''s feelings.', 'F'),
(3, 43,  'I find it deeply uncomfortable to be in conflict with people I care about.', 'F'),
(3, 44,  'I place a high value on empathy and compassion when evaluating situations.', 'F'),
(3, 45,  'I often make exceptions to rules when a person''s unique circumstances warrant it.', 'F'),
-- J/P
(4, 46,  'I like to have a clear plan before I start a project.', 'J'),
(4, 47,  'I feel anxious or unsettled when things are left unresolved or open-ended.', 'J'),
(4, 48,  'I prefer to make decisions quickly so I can move forward rather than keeping options open.', 'J'),
(4, 49,  'I keep an organised calendar and rarely miss deadlines.', 'J'),
(4, 50,  'I feel most productive when my environment is tidy and structured.', 'J'),
(4, 51,  'I find it satisfying to finish tasks well ahead of a deadline.', 'J'),
(4, 52,  'I prefer a predictable routine over spontaneous changes of plan.', 'J'),
(4, 53,  'I work best when I complete one task fully before moving to the next.', 'J'),
(4, 54,  'I enjoy keeping my options open rather than committing to a fixed plan.', 'P'),
(4, 55,  'I work well under pressure and often find deadlines motivating.', 'P'),
(4, 56,  'I like to adapt and improvise rather than follow a set schedule.', 'P'),
(4, 57,  'I find strict routines and rigid structures limiting.', 'P'),
(4, 58,  'I tend to start many projects and return to them when inspiration strikes.', 'P'),
(4, 59,  'I enjoy exploring new information even when it might change my mind at the last minute.', 'P'),
(4, 60,  'I find it exciting rather than stressful to adjust plans on the fly.', 'P'),
-- Additional balanced set (61–120)
(1, 61,  'I find small talk with strangers enjoyable and natural.', 'E'),
(1, 62,  'I often seek out social events as a way to unwind after a long week.', 'E'),
(1, 63,  'I get bored quickly when spending too much time alone.', 'E'),
(1, 64,  'I am comfortable speaking up in meetings without preparing in advance.', 'E'),
(1, 65,  'I feel comfortable being the person who initiates group activities.', 'E'),
(1, 66,  'I find prolonged periods of solitude uncomfortable or lonely.', 'E'),
(1, 67,  'I prefer to process emotions by talking them through with someone.', 'E'),
(1, 68,  'I enjoy being part of a large, active team.', 'E'),
(1, 69,  'I prefer reading, journaling, or other solitary activities as a way to unwind.', 'I'),
(1, 70,  'I find phone calls or unplanned interruptions draining.', 'I'),
(1, 71,  'I often rehearse what I want to say before joining a conversation.', 'I'),
(1, 72,  'I prefer sending a message over making a spontaneous phone call.', 'I'),
(1, 73,  'I feel most like myself when I have extended time to reflect.', 'I'),
(1, 74,  'I tend to share personal thoughts only with people I trust deeply.', 'I'),
(1, 75,  'I find working from home or in a quiet private space more productive.', 'I'),
(2, 76,  'I am good at noticing small, practical details others overlook.', 'S'),
(2, 77,  'I prefer recipes, manuals, or clear instructions over improvising.', 'S'),
(2, 78,  'I find abstract theories uninteresting unless they have practical application.', 'S'),
(2, 79,  'I draw on past experience more than imagination when solving problems.', 'S'),
(2, 80,  'I prefer incremental, steady progress over dramatic leaps of change.', 'S'),
(2, 81,  'I tend to be literal and precise in how I communicate.', 'S'),
(2, 82,  'I focus on what has worked before rather than experimenting with the unknown.', 'S'),
(2, 83,  'I value practicality and common sense above creativity or originality.', 'S'),
(2, 84,  'I am drawn to abstract ideas, even when they have no obvious practical use.', 'N'),
(2, 85,  'I often read between the lines rather than taking things at face value.', 'N'),
(2, 86,  'I quickly become bored by tasks that require rote repetition.', 'N'),
(2, 87,  'I enjoy thought experiments and exploring ideas that may never become reality.', 'N'),
(2, 88,  'I tend to explain things through metaphors, analogies, or stories.', 'N'),
(2, 89,  'I am excited by the potential of emerging technologies or new paradigms.', 'N'),
(2, 90,  'I find myself imagining alternative outcomes or different versions of events.', 'N'),
(3, 91,  'I can separate my personal feelings from a professional decision with relative ease.', 'T'),
(3, 92,  'I find debates and intellectual challenges stimulating rather than threatening.', 'T'),
(3, 93,  'I am more concerned with whether something is correct than whether it feels right.', 'T'),
(3, 94,  'I tend to push back on ideas I consider illogical, even if others are invested in them.', 'T'),
(3, 95,  'I believe the most helpful thing is often the most honest, even if it stings.', 'T'),
(3, 96,  'I distrust decisions that are driven primarily by emotion.', 'T'),
(3, 97,  'I find it easier to stay calm under pressure because I rely on reasoning over reaction.', 'T'),
(3, 98,  'I evaluate my own performance with the same critical standard I apply to others.', 'T'),
(3, 99,  'I find it meaningful to offer support and encouragement to people around me.', 'F'),
(3,100,  'I notice when someone is struggling emotionally, even if they have not said anything.', 'F'),
(3,101,  'I tend to prioritise group harmony over winning an argument.', 'F'),
(3,102,  'I feel deeply affected by stories of others'' suffering, even strangers.', 'F'),
(3,103,  'I prefer environments where people feel emotionally safe to express themselves.', 'F'),
(3,104,  'I find it difficult to remain neutral when someone I care about is hurting.', 'F'),
(3,105,  'I consider the emotional tone of a message as important as its factual content.', 'F'),
(4,106,  'I write to-do lists and feel genuine satisfaction when I cross items off.', 'J'),
(4,107,  'I find it hard to relax when I know there are unfinished tasks waiting.', 'J'),
(4,108,  'I prefer to know the agenda before attending a meeting.', 'J'),
(4,109,  'I feel uncomfortable when plans change at the last minute.', 'J'),
(4,110,  'I tend to make commitments and stick to them reliably.', 'J'),
(4,111,  'I prefer to settle matters and reach conclusions rather than leaving things open.', 'J'),
(4,112,  'I like my living and working space to be organised and clutter-free.', 'J'),
(4,113,  'I feel most productive when following a structured daily routine.', 'J'),
(4,114,  'I like starting something without knowing exactly how it will turn out.', 'P'),
(4,115,  'I find it easy to shift gears when something unexpected comes up.', 'P'),
(4,116,  'I tend to gather more information before making a final decision.', 'P'),
(4,117,  'I work in bursts of energy rather than at a steady, scheduled pace.', 'P'),
(4,118,  'I find rigid rules and procedures stifling.', 'P'),
(4,119,  'I often leave tasks open so I can revisit them with fresh ideas.', 'P'),
(4,120,  'I prefer a spontaneous, unplanned day off over one with a full itinerary.', 'P')
on conflict (question_number) do nothing;

create table if not exists public.personality_options (
  id serial primary key,
  value int not null unique,
  label text not null,
  created_at timestamptz default now()
);

insert into public.personality_options (value, label) values
  (0, 'Strongly Disagree'),
  (1, 'Disagree'),
  (2, 'Neutral'),
  (3, 'Agree'),
  (4, 'Strongly Agree')
on conflict (value) do nothing;

create table if not exists public.personality_types (
  id serial primary key,
  code char(4) not null unique,
  title text not null,
  archetype text not null,
  description text not null,
  strengths text not null,
  growth_areas text not null,
  created_at timestamptz default now()
);

insert into public.personality_types (code, title, archetype, description, strengths, growth_areas) values
('INTJ', 'Architect', 'The Strategist',
 'INTJs are strategic, independent thinkers who see the world as a chessboard of possibilities. They set high standards for themselves and others, and are driven to turn complex ideas into concrete plans.',
 'Long-term thinking, intellectual depth, decisive, self-confident, determined',
 'May appear cold or arrogant; struggles with emotional expression; can be overly critical'),
('INTP', 'Logician', 'The Thinker',
 'INTPs are inventive, analytical minds who love exploring theoretical ideas. They prize accuracy and logic above all else, and often pursue knowledge for its own sake.',
 'Abstract reasoning, objectivity, original ideas, open-minded, precise',
 'Can be indecisive or detached; may struggle to follow through; difficulty with routine tasks'),
('ENTJ', 'Commander', 'The Leader',
 'ENTJs are bold, imaginative, and strong-willed. They are natural leaders who enjoy organising people and resources toward long-term goals and are comfortable making difficult decisions.',
 'Strategic, decisive, efficient, confident, charismatic leader',
 'Can be domineering or impatient; may undervalue emotional concerns; intolerant of inefficiency'),
('ENTP', 'Debater', 'The Innovator',
 'ENTPs are smart, curious individuals who cannot resist an intellectual challenge. They love to brainstorm, debate, and question assumptions — often playing devil''s advocate.',
 'Quick-thinking, adaptable, knowledgeable, charismatic, ideas-driven',
 'May argue for the sake of arguing; can lose interest once the challenge is solved; struggles with follow-through'),
('INFJ', 'Advocate', 'The Counsellor',
 'INFJs are insightful, principled, and deeply committed to their values. They seek meaning in relationships and work, and are driven by a desire to help others and improve the world.',
 'Empathetic, visionary, determined, passionate, altruistic',
 'Can be perfectionistic or private to a fault; prone to burnout; difficulty with criticism'),
('INFP', 'Mediator', 'The Idealist',
 'INFPs are imaginative, empathetic individuals guided by their values. They are deeply curious about people and ideas, and seek to live in alignment with what they believe is good and true.',
 'Creative, open-minded, compassionate, dedicated, idealistic',
 'May be overly idealistic; can take criticism personally; struggles with practical day-to-day tasks'),
('ENFJ', 'Protagonist', 'The Teacher',
 'ENFJs are charismatic, empathetic leaders who are drawn to helping others reach their potential. They are highly attuned to the needs of those around them and are motivated by a sense of shared purpose.',
 'Warm, organised, loyal, persuasive, natural mentor',
 'Can be overly idealistic about people; may neglect own needs; can struggle with conflict'),
('ENFP', 'Campaigner', 'The Champion',
 'ENFPs are enthusiastic, creative, and sociable free spirits who see life as full of possibilities. They form deep connections with others and are driven by a desire to inspire and be inspired.',
 'Energetic, empathetic, creative, optimistic, people-focused',
 'May be disorganised or easily distracted; overly emotional at times; struggles with follow-through'),
('ISTJ', 'Logistician', 'The Inspector',
 'ISTJs are practical, responsible, and dependable. They honour their commitments and believe in doing things correctly. They are careful, meticulous, and find comfort in clear rules and structures.',
 'Reliable, organised, hardworking, honest, detail-oriented',
 'Can be inflexible or resistant to change; may be overly critical of deviation from procedure'),
('ISFJ', 'Defender', 'The Protector',
 'ISFJs are warm, dedicated individuals who take great care of those around them. They are highly attuned to others'' emotions and needs, and find fulfilment in service and reliability.',
 'Supportive, patient, reliable, observant, committed',
 'May struggle to assert own needs; can be overly selfless; uncomfortable with change or conflict'),
('ESTJ', 'Executive', 'The Supervisor',
 'ESTJs are organised, assertive, and practical. They value order, tradition, and clear expectations. They are natural administrators who excel at managing people and processes.',
 'Efficient, leadership, loyal, patient, organised',
 'Can be rigid, judgmental, or controlling; may overlook emotional dimensions of situations'),
('ESFJ', 'Consul', 'The Provider',
 'ESFJs are caring, social, and popular individuals who enjoy being in positions where they can help and support others. They are loyal and are deeply aware of their responsibilities to family and community.',
 'Warm, caring, loyal, sociable, team-oriented',
 'Can be overly sensitive to criticism; may prioritise others'' approval too highly; struggles with change'),
('ISTP', 'Virtuoso', 'The Craftsman',
 'ISTPs are bold, practical experimenters who thrive on understanding how things work. They are observant and quiet until a problem needs solving — then they leap into action with creative solutions.',
 'Analytical, practical, calm, direct, resourceful',
 'Can be insensitive or overly private; may get bored quickly; struggles with long-term planning'),
('ISFP', 'Adventurer', 'The Artist',
 'ISFPs are flexible, charming, and sensitive individuals who live in the moment. They are deeply attuned to their senses and express themselves through creative action rather than words.',
 'Imaginative, passionate, curious, artistic, kind',
 'May avoid conflict to a fault; can be unpredictable; struggles with long-term goals'),
('ESTP', 'Entrepreneur', 'The Dynamo',
 'ESTPs are energetic, perceptive, and dramatic risk-takers. They love being at the centre of the action, responding to real-world problems with practical, immediate solutions.',
 'Bold, direct, observant, sociable, original',
 'May be impatient or insensitive; can be risk-prone; struggles with abstract planning'),
('ESFP', 'Entertainer', 'The Performer',
 'ESFPs are spontaneous, energetic, and enthusiastic people-lovers. They are the life of the party and genuinely enjoy being around others, bringing joy and fun wherever they go.',
 'Bold, original, observant, excellent people skills, showmanship',
 'May avoid long-term planning; can be easily bored; struggles with difficult or abstract conversations')
on conflict (code) do nothing;

create or replace view public.personality_questions_full as
  select
    q.id,
    q.question_number,
    q.question_text,
    q.scored_pole,
    d.code as dichotomy,
    d.pole_a,
    d.pole_b,
    d.label_a,
    d.label_b
  from public.personality_questions q
  join public.personality_dichotomies d on d.id = q.dichotomy_id
  order by q.question_number;
